resource_types:
- name: resource-proxy
  type: registry-image
  source:
    repository: suhlig/concourse-resource-proxy
    tag: 1.0.0-pre7

resources:
- name: every-5min-proxied
  source:
    url: wss://proxy.uhlig.it
    token: ((proxy-api-token))
    proxied:
      interval: 5m # this is passed to the resource under development as source
  type: resource-proxy

jobs:
- name: announce
  plan:
  - get: every-5min-proxied
    trigger: true
  - task: show-time
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: alpine }
      inputs:
      - name: every-5min-proxied
      run:
        path: sh
        args:
          - -c
          - |
            echo input
            cat every-5min-proxied/input
            echo
            echo timestamp
            cat every-5min-proxied/timestamp
  - put: every-5min-proxied
