jobs:
  # Create a new tag in order to trigger this
  - name: test-and-ship-tag
    plan:
      - in_parallel:
        - get: tagged-commits
          trigger: true
        - get: tasks
      - task: build-image
        privileged: true
        file: tasks/oci/build-image.yml
        input_mapping: { source: tagged-commits }
      - load_var: image-version
        file: tagged-commits/.git/describe_ref # https://github.com/concourse/git-resource#additional-files-populated
      - put: docker-hub
        params:
          image: image/image.tar
          version: ((.:image-version))
          bump_aliases: true
      - task: compile-release-notes
        file: tasks/git/release-notes.yml
        input_mapping: { repo: tagged-commits }
        output_mapping: { release-notes: release-notes }
      - put: gh-release
        params:
          name: tagged-commits/.git/ref
          body: release-notes/commits-since-last-tag.txt
          tag: tagged-commits/.git/ref
        on_success:
          do:
            - task: create-publication-message
              file: tasks/git/create-release-message.yml
              input_mapping: { source: tagged-commits }
              params: { project_name: concourse-resource-proxy }
              output_mapping: { message: telegram-message }
            - put: telegram-notification
              params:
                chat_id: ((telegram.chat_id))
                text_file: telegram-message/new-release.txt

resources:
  - name: tagged-commits
    type: git
    icon: github
    source:
      uri: git@github.com:suhlig/concourse-resource-proxy.git
      private_key: ((github.ssh_key))
      fetch_tags: true
      tag_filter: v*

  - name: tasks
    type: git
    icon: github
    source:
      uri: git@github.com:suhlig/concourse-task-store.git
      private_key: ((github.ssh_key))

  - name: docker-hub
    type: registry-image
    icon: docker
    source:
      repository: suhlig/concourse-resource-proxy
      username: suhlig
      password: ((dockerhub.auth_token))

  - name: gh-release
    type: github-release
    icon: github-circle
    source:
      owner: suhlig
      repository: concourse-resource-proxy
      access_token: ((github.token))
      pre_release: true
      drafts: true

  - name: telegram-notification
    type: telegram-notification
    icon: telegram
    source:
      bot_token: ((telegram.bot_token))

resource_types:
  - name: telegram-notification
    type: docker-image
    source:
      repository: w32blaster/concourse-telegram-notifier
